version: 2

models:
  - name: dim_airing
    description: "Dimension table for airing schedult of anime series."
    columns:
      - name: anime_id
        description: "Primary key of this table, were replaced with a surrogate key combine of anime_id and aired_from."
        tests:
          - not_null
          - unique
        
      - name: aired_from
        description: "Anime on board date"
        tests:
          - not_null

      - name: aired_to
        description: "Anime end date"
        tests:
          - dbt_utils.expression_is_true:
              expression: "is null or aired_to >= aired_from"
  
  - name: dim_info
    description: "Dimension table for anime information."
    columns:
      - name: anime_id
        description: "Primary key of this table, were replaced with a surrogate key combine of anime_id and aired_from."
        tests:
          - not_null
          - unique

      - name: title
        description: "Title of the anime."
        tests:
          - not_null
      
      - name: type
        description: "Anime type"
        tests:
          - not_null

      - name: status
        description: "Current status of the anime"
        tests:
          - not_null
              
  - name: dim_season
    description: "Dimension table of seasonal information."
    columns:
      - name: anime_id
        description: "Primary key of this table, were replaced with a surrogate key combine of anime_id and aired_from."
        tests:
          - not_null
          - unique

      - name: season
        description: "Release season"
        tests:
          - accepted_values:
              arguments:
                values: ['winter', 'spring', 'summer', 'fall']
      
      - name: year
        description: "Release year"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1900
                max_value: 2100

  - name: dim_studios
    description: "Dimension table of anime studios."
    columns:
      - name: anime_id
        description: "Primary key of this table, were replaced with a surrogate key combine of anime_id and aired_from."
        tests:
          - not_null
          - unique

      - name: studios
        description: "Studios who produced this anime"

  - name: fact_anime
    description: "Fact table of anime with metrics."
    columns:
      - name: anime_id
        description: "Primary key of this table, were replaced with a surrogate key combine of anime_id and aired_from."
        tests:
          - not_null
          - unique

      - name: episodes
        description: "Number of episodes"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 2000

      - name: score
        description: "Anime score from users"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 10
      
      - name: scored_by
        description: "Number of users who scored this anime"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: popularity
        description: "Popularity rank based on users list"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: members
        description: "Number of members who have this anime in their list"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
      
      - name: favorites
        description: "Number of users who have this anime in their favorite list"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
      
      - name: ranking
        description: "Ranking based on users score"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

